# -*- coding: utf-8 -*-
"""Robot_Configuration_&_DOF_Explorer V2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt42YeFrIqopic2FgHw_C5oSQ2gGJXWH
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

L1 = 4
L2 = 3
L3 = 2

joint1 = widgets.IntSlider(
    value=45,
    min=-180,
    max=180,
    description='Joint1'
)

joint2 = widgets.IntSlider(
    value=30,
    min=-180,
    max=180,
    description='Joint2'
)

joint3 = widgets.IntSlider(
    value=60,
    min=-180,
    max=180,
    description='Joint3'
)

def draw_robot(theta1, theta2, theta3):

    # Convert degrees to radians
    t1 = np.radians(theta1)
    t2 = np.radians(theta2)
    t3 = np.radians(theta3)

    # Joint 1 position
    x1 = L1 * np.cos(t1)
    y1 = L1 * np.sin(t1)

    # Joint 2 position
    x2 = x1 + L2 * np.cos(t1 + t2)
    y2 = y1 + L2 * np.sin(t1 + t2)

    # End Effector position
    x3 = x2 + L3 * np.cos(t1 + t2 + t3)
    y3 = y2 + L3 * np.sin(t1 + t2 + t3)

    # Create Plot
    plt.figure(figsize=(7,7))

    # Link 1
    plt.plot(
        [0, x1],
        [0, y1],
        marker='o',
        linewidth=4
    )

    # Link 2
    plt.plot(
        [x1, x2],
        [y1, y2],
        marker='o',
        linewidth=4
    )

    # Link 3
    plt.plot(
        [x2, x3],
        [y2, y3],
        marker='o',
        linewidth=4
    )

    plt.xlim(-10, 10)
    plt.ylim(-10, 10)

    plt.grid()

    plt.title(
        f"3 DOF Robot Arm | End Effector = ({x3:.2f}, {y3:.2f})"
    )

    plt.show()


widgets.interactive(
    draw_robot,
    theta1=joint1,
    theta2=joint2,
    theta3=joint3
)